version: '3.8'

services:
  db:
    image: postgres:15
    container_name: local_postgres
    ports:
      - "5433:5432"               # ← host:container
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: app_db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
